packages:
  - apps/*
  - packages/*

overrides:
  sharp: 0.35.2
  postcss: 8.5.18

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - better-sqlite3
  - esbuild
  - sharp

minimumReleaseAgeExclude:
  - '@ai-sdk/anthropic@4.0.42'
  - '@ai-sdk/gateway@4.0.64'
  - '@ai-sdk/google@4.0.51'
  - '@ai-sdk/openai@4.0.47'
  - '@ai-sdk/provider-utils@5.0.30'
  - '@ai-sdk/provider@4.0.8'
  - '@ai-sdk/xai@4.0.44'
  - ai@7.0.79
  - '@ai-sdk/alibaba@2.0.35'
  - '@ai-sdk/baseten@2.1.15'
  - '@ai-sdk/cerebras@3.0.37'
  - '@ai-sdk/cohere@4.0.30'
  - '@ai-sdk/deepinfra@3.0.37'
  - '@ai-sdk/deepseek@3.0.32'
  - '@ai-sdk/fireworks@3.0.40'
  - '@ai-sdk/groq@4.0.31'
  - '@ai-sdk/huggingface@2.0.37'
  - '@ai-sdk/mistral@4.0.33'
  - '@ai-sdk/moonshotai@3.0.38'
  - '@ai-sdk/openai-compatible@3.0.37'
  - '@ai-sdk/perplexity@4.0.32'
  - '@ai-sdk/togetherai@3.0.38'

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  better-sqlite3: true
  esbuild: true
  sharp: true
