"use client"

import { useMemo, useState } from "react"
import { ActionButton, DisabledReason, Panel } from "./Primitives"

type JobState = "RENDERING" | "QUEUED" | "COMPLETED" | "FAILED" | "CANCEL_REQUESTED" | "EXPIRED"
type DeliveryState = "PUBLISHED" | "AWAITING_T5" | "FAILED" | "EXPIRED"
type Job = Readonly<{ id: string; tenant: string; state: JobState; delivery: DeliveryState; progress?: number; stale?: boolean; retryable: boolean; attempts: number }>

const initialJobs: readonly Job[] = [
  { id: "RND-8991-X", tenant: "Aethelgard Dynamics", state: "RENDERING", delivery: "AWAITING_T5", progress: 50, stale: true, retryable: false, attempts: 2 },
  { id: "RND-8990-W", tenant: "Omni Consumer Corp", state: "COMPLETED", delivery: "PUBLISHED", retryable: false, attempts: 1 },
  { id: "RND-8992-Y", tenant: "Tyrell Corporation", state: "QUEUED", delivery: "AWAITING_T5", retryable: false, attempts: 1 },
  { id: "RND-8985-V", tenant: "Cyberdyne Systems", state: "COMPLETED", delivery: "PUBLISHED", retryable: false, attempts: 3 },
  { id: "RND-8970-T", tenant: "Nakamura Labs", state: "FAILED", delivery: "FAILED", retryable: false, attempts: 2 },
  { id: "RND-8968-S", tenant: "Omni Consumer Corp", state: "EXPIRED", delivery: "EXPIRED", retryable: true, attempts: 2 },
]

const statusText = (job: Job): string => job.state === "RENDERING" ? `[${job.state} ${job.progress ?? 0}%]` : `[${job.state}]`
const downloadable = (job: Job): boolean => job.state === "COMPLETED" && job.delivery === "PUBLISHED"
const disabledProps = (reason: string | undefined): Readonly<{ disabledReason?: string }> => reason === undefined ? {} : { disabledReason: reason }

export function JobQueue() {
  const [jobs, setJobs] = useState<readonly Job[]>(initialJobs)
  const [filter, setFilter] = useState("ALL")
  const [query, setQuery] = useState("")
  const [page, setPage] = useState(1)
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [notice, setNotice] = useState("Live refresh connected · last sync just now")
  const [confirmId, setConfirmId] = useState<string | null>(null)
  const [refreshing, setRefreshing] = useState(false)

  const filtered = useMemo(() => jobs.filter((job) => (filter === "ALL" || job.state === filter) && `${job.id} ${job.tenant}`.toLowerCase().includes(query.toLowerCase())), [filter, jobs, query])
  const visible = filtered.slice((page - 1) * 4, page * 4)
  const selected = jobs.find((job) => job.id === selectedId)
  const counts = { queued: jobs.filter((job) => job.state === "QUEUED").length, rendering: jobs.filter((job) => job.state === "RENDERING" || job.state === "CANCEL_REQUESTED").length, completed: jobs.filter((job) => job.state === "COMPLETED").length, failed: jobs.filter((job) => job.state === "FAILED").length }

  const refresh = () => { setRefreshing(true); window.setTimeout(() => { setRefreshing(false); setNotice("Live refresh connected · last sync just now") }, 350) }
  const cancel = (id: string) => { setJobs((current) => current.map((job) => job.id === id ? { ...job, state: "CANCEL_REQUESTED" } : job)); setConfirmId(null); setNotice("Cancel requested · waiting for worker acknowledgement") }
  const retry = (job: Job) => { if (!job.retryable) return; setJobs((current) => current.map((item) => item.id === job.id ? { ...item, state: "QUEUED", delivery: "AWAITING_T5", attempts: item.attempts + 1 } : item)); setNotice(`Retry queued for ${job.id}; previous attempts preserved`) }
  const download = (kind: string, job: Job) => { if (!downloadable(job)) return; setNotice(`${kind} download prepared for ${job.id} · expires in 24 hours`) }

  return <div className="job-page">
    <header className="job-header"><div><a className="wordmark" href="/workflow">REF_STUDIO</a><nav aria-label="Workflow destinations"><a href="/workflow">Workflow</a><a href="/admin">Admin</a><a href="/docs">Docs</a><a href="/support">Support</a></nav></div><div className="job-header-actions"><button data-control-id="job_queue_delivery:1" type="button" onClick={() => setNotice("Notifications: queue, approval, and delivery alerts enabled")}>Notifications</button><button data-control-id="job_queue_delivery:2" type="button" onClick={() => setNotice("Settings: workspace delivery policy is read-only")}>Settings</button><a data-control-id="job_queue_delivery:3" className="button button-primary" href="/projects/new">New Project</a></div></header>
    <main className="job-main"><div className="job-title-row"><div><p className="eyebrow">ACTIVE ENGINE TASKS · ASSET RETRIEVAL</p><h1>Queue &amp; Delivery</h1><p className="job-subtitle">Operational state is authoritative; frame progress never implies approval.</p></div><button data-control-id="job_queue_delivery:4" type="button" onClick={refresh}>{refreshing ? "Refreshing…" : "Refresh queue"}</button></div>
      <div className="job-counts" aria-label="Canonical state counts"><span>QUEUED <b>{counts.queued}</b></span><span>RENDERING <b>{counts.rendering}</b></span><span>COMPLETED <b>{counts.completed}</b></span><span>FAILED <b>{counts.failed}</b></span></div>
      <Panel className="job-panel"><div className="job-tools"><input data-control-id="job_queue_delivery:5" aria-label="Search jobs" value={query} onChange={(event) => { setQuery(event.target.value); setPage(1) }} placeholder="Search job or tenant" /><label>State <select aria-label="Filter state" data-control-id="job_queue_delivery:6" value={filter} onChange={(event) => { setFilter(event.target.value); setPage(1) }}><option>ALL</option><option>QUEUED</option><option>RENDERING</option><option>COMPLETED</option><option>FAILED</option><option>EXPIRED</option></select></label><div className="job-global-actions"><button data-control-id="job_queue_delivery:7" type="button" onClick={() => selectedId ? setSelectedId(selectedId) : setNotice("Select a job to open")}>Open selected</button><button data-control-id="job_queue_delivery:8" type="button" onClick={() => selectedId ? setConfirmId(selectedId) : setNotice("Select a job before cancelling")}>Cancel selected</button><button data-control-id="job_queue_delivery:9" type="button" onClick={() => selected ? retry(selected) : setNotice("Select a retryable job")}>Retry selected</button><button data-control-id="job_queue_delivery:10" type="button" disabled title="Prioritize is disabled for the authoritative queue">Prioritize</button><button data-control-id="job_queue_delivery:13" type="button" onClick={() => selectedId ? setSelectedId(selectedId) : setNotice("Select a job for detail")}>Detail</button><button data-control-id="job_queue_delivery:14" type="button" onClick={() => setNotice("Receipt index opened")}>Receipt</button><button data-control-id="job_queue_delivery:15" type="button" disabled={!selected || !downloadable(selected)}>Report</button><button data-control-id="job_queue_delivery:16" type="button" disabled={!selected || !downloadable(selected)}>Video</button><button data-control-id="job_queue_delivery:21" type="button" onClick={() => setConfirmId(null)}>Keep job</button><button data-control-id="job_queue_delivery:22" type="button" onClick={() => confirmId ? cancel(confirmId) : setNotice("No cancellation request is pending")}>Request cancel</button></div></div>
        <p className="job-notice" role="status">{notice}</p><div className="job-table-wrap"><table><thead><tr><th>JOB_ID</th><th>TENANT</th><th>STATE</th><th>DELIVERY</th><th>ACTIONS</th></tr></thead><tbody>{visible.map((job) => <tr key={job.id}><td><button data-job-action="open" className="link-button" type="button" onClick={() => setSelectedId(job.id)}>#{job.id}</button></td><td>{job.tenant}</td><td><span className={`status status-${job.state.toLowerCase()}`}>{statusText(job)}</span>{job.stale && <small className="stale">STALE LAST-KNOWN</small>}</td><td><span className="mono">{job.delivery}</span></td><td className="actions"><button data-job-action="cancel" type="button" disabled={job.state === "COMPLETED" || job.state === "EXPIRED"} onClick={() => setConfirmId(job.id)}>Cancel</button><button data-job-action="retry" type="button" disabled={!job.retryable} title={job.retryable ? undefined : "This failure is non-retryable"} onClick={() => retry(job)}>Retry</button><button data-job-action="prioritize" type="button" disabled title="Prioritize is disabled for the authoritative queue">Prioritize</button></td></tr>)}</tbody></table></div>
        <div className="job-footer"><span>SHOWING {visible.length ? (page - 1) * 4 + 1 : 0}-{Math.min(page * 4, filtered.length)} OF {filtered.length} JOBS</span><div><button data-control-id="job_queue_delivery:11" type="button" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><button data-control-id="job_queue_delivery:12" type="button" disabled={page * 4 >= filtered.length} onClick={() => setPage(page + 1)}>Next</button></div></div></Panel>
      {selected && <Panel className="job-detail" aria-labelledby="job-detail-title"><div className="detail-heading"><div><p className="eyebrow">JOB DETAIL</p><h2 id="job-detail-title">#{selected.id}</h2></div><button type="button" onClick={() => setSelectedId(null)}>Close</button></div><p>{selected.tenant} · {selected.state} · delivery {selected.delivery}</p><h3>Attempt history</h3><ol className="attempts">{Array.from({ length: selected.attempts }, (_, index) => <li key={index}>Attempt {index + 1} · {index === selected.attempts - 1 ? selected.state : "RETAINED"} · receipt <a href={`/admin/receipts/${selected.id}-${index + 1}`}>view receipt</a></li>)}</ol><p className="job-subtitle">T5 approval: {selected.delivery === "PUBLISHED" ? "approved" : "pending"}. This is separate from render frame progress.</p><div className="download-actions"><ActionButton sourceId="job_queue_delivery:15" operationId={`report:${selected.id}`} state={downloadable(selected) ? "enabled" : "disabled"} {...disabledProps(downloadable(selected) ? undefined : "Report unavailable until valid publication; staged, partial, failed, foreign, and expired artifacts are denied")} onClick={() => download("Render report", selected)}>Download report</ActionButton><ActionButton sourceId="job_queue_delivery:16" operationId={`video:${selected.id}`} state={downloadable(selected) ? "enabled" : "disabled"} {...disabledProps(downloadable(selected) ? undefined : "Video unavailable until valid publication; link is expiring")} onClick={() => download("Video", selected)}>Download video</ActionButton></div></Panel>}
      <footer className="job-footer-nav"><a data-control-id="job_queue_delivery:17" href="/docs">API</a><a data-control-id="job_queue_delivery:18" href="/legal">Legal</a><a data-control-id="job_queue_delivery:19" href="/privacy">Privacy</a><a data-control-id="job_queue_delivery:20" href="/support">Support</a><button data-control-id="job_queue_delivery:23" type="button" onClick={() => setNotice("Queue view: all tenants")}>All tenants</button><button data-control-id="job_queue_delivery:24" type="button" onClick={() => setNotice("Receipt index opened")}>Receipt index</button><button data-control-id="job_queue_delivery:25" type="button" onClick={() => setNotice("Staged artifacts remain private")}>Delivery policy</button><button data-control-id="job_queue_delivery:26" type="button" onClick={() => setNotice("Refresh interval: 10 seconds")}>Refresh policy</button><button data-control-id="job_queue_delivery:27" type="button" onClick={() => setNotice("Notifications are enabled")}>Alert policy</button><button data-control-id="job_queue_delivery:28" type="button" onClick={() => setNotice("Export is bounded to visible queue metadata")}>Export view</button><button data-control-id="job_queue_delivery:29" type="button" onClick={() => setNotice("Keyboard shortcuts: / search, r refresh")}>Shortcuts</button><button data-control-id="job_queue_delivery:30" type="button" onClick={() => setNotice("Queue health nominal")}>Queue health</button></footer>
    </main>{confirmId && <div className="confirm-backdrop" role="dialog" aria-modal="true" aria-labelledby="cancel-title"><Panel className="confirm"><h2 id="cancel-title">Cancel job?</h2><p>This requests cancellation. The job will remain visible as CANCEL_REQUESTED until the worker acknowledges it.</p><button type="button" onClick={() => setConfirmId(null)}>Keep job</button><button type="button" onClick={() => cancel(confirmId)}>Request cancel</button></Panel></div>}
    <DisabledReason id="job-controls-reason" reason="Job actions are governed by authoritative lifecycle state." />
  </div>
}
