"use client"

import { useEffect, useMemo, useState } from "react"
import { ActionButton, DisabledReason, Panel } from "./Primitives"

type Status = "QUARANTINED" | "CRITICAL_QUARANTINE"
type Item = Readonly<{ id: string; displayId: string; tenantId: string; reason: string; status: Status; retention: string; declared: string; detected: string; magic: string; size: string; parse: string; release: boolean; releaseReason: string; history: readonly string[] }>

const items: readonly [Item, ...Item[]] = [
  { id: "qitem_8992_fx", displayId: "QT-8992-FX", tenantId: "tnt_aegis", reason: "VIDEO_TYPE_INVALID", status: "QUARANTINED", retention: "12h 45m", declared: "video/mp4", detected: "application/octet-stream", magic: "ftyp signature absent", size: "842 MB", parse: "FAILED · container unreadable", release: true, releaseReason: "", history: ["08:21 · quarantine enforced · scanner", "08:20 · upload finalized · ingest"] },
  { id: "qitem_8993_al", displayId: "QT-8993-AL", tenantId: "tnt_aegis", reason: "MALWARE_SIGNATURE_DETECTED", status: "CRITICAL_QUARANTINE", retention: "00h 12m", declared: "video/mp4", detected: "video/mp4", magic: "ftyp present · signature hit", size: "1.2 GB", parse: "BLOCKED · malware verdict", release: false, releaseReason: "Release blocked: failed malware and parse checks.", history: ["08:31 · critical quarantine · scanner", "08:30 · signature match · detector"] },
  { id: "qitem_8994_zn", displayId: "QT-8994-ZN", tenantId: "tnt_orbit", reason: "METADATA_CORRUPTION", status: "QUARANTINED", retention: "48h 00m", declared: "video/quicktime", detected: "video/mp4", magic: "ftyp present · brand mismatch", size: "428 MB", parse: "FAILED · metadata inconsistent", release: false, releaseReason: "Release blocked: acting scope does not include this tenant.", history: ["07:54 · quarantine enforced · scanner", "07:53 · metadata parse failed · parser"] },
  { id: "qitem_8995_mv", displayId: "QT-8995-MV", tenantId: "tnt_northstar", reason: "PARSE_TIMEOUT", status: "QUARANTINED", retention: "06h 10m", declared: "video/mp4", detected: "video/mp4", magic: "ftyp present · truncated payload", size: "2.1 GB", parse: "TIMEOUT · safe parser limit", release: false, releaseReason: "Release unavailable: validation failure keeps input isolated.", history: ["06:12 · quarantine enforced · parser", "06:11 · parse timeout · parser"] },
]
const firstItem = items[0]

const control = (number: number): string => `admin_quarantine:${number}`

export function QuarantineReview() {
  const [selectedId, setSelectedId] = useState(firstItem.id)
  const [filter, setFilter] = useState("ALL")
  const [query, setQuery] = useState("")
  const [page, setPage] = useState(1)
  const [dialog, setDialog] = useState<"release" | "reject" | null>(null)
  const [confirmed, setConfirmed] = useState(false)
  const [notice, setNotice] = useState("System safe mode active · all inputs remain isolated")
  const [revalidation, setRevalidation] = useState<string | null>(null)
  const [inspection, setInspection] = useState<string | null>(null)
  const selected = useMemo(() => items.find((item) => item.id === selectedId) ?? firstItem, [selectedId])
  const visible = items.filter((item) => (filter === "ALL" || item.status === filter) && `${item.displayId} ${item.reason} ${item.tenantId}`.toLowerCase().includes(query.toLowerCase()))

  useEffect(() => { const id = new URLSearchParams(window.location.search).get("item"); if (id && items.some((item) => item.id === id)) setSelectedId(id) }, [])
  useEffect(() => { if (!dialog) return; const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") setDialog(null) }; window.addEventListener("keydown", closeOnEscape); return () => window.removeEventListener("keydown", closeOnEscape) }, [dialog])
  const choose = (id: string) => { setSelectedId(id); window.history.replaceState(null, "", `/admin/quarantine?item=${encodeURIComponent(id)}`) }
  const openDialog = (kind: "release" | "reject") => { setConfirmed(false); setDialog(kind) }
  const submit = () => {
    if (!confirmed) return
    if (dialog === "release") { const next = `upload_${selected.id}_revalidation`; setRevalidation(next); setNotice(`Audit result recorded · linked revalidation ${next} is VALIDATING · original ${selected.id} remains QUARANTINED`) }
    else setNotice(`Audit result recorded · ${selected.id} rejected · input remains isolated`)
    setDialog(null)
  }
  return <div className="admin-page quarantine-page">
    <header className="admin-page-header"><div><p className="eyebrow">OPERATIONS / CONTAINMENT</p><h1>Quarantine</h1><p className="admin-subtitle">Isolated inputs requiring manual review. Evidence is safe, bounded, and append-only.</p></div><span className="status status-blocked">SYSTEM SAFE MODE ACTIVE</span></header>
    <p className="admin-notice" role="status" aria-live="polite">{notice}</p>
    <Panel className="quarantine-toolbar"><label>Search evidence<input aria-label="Search quarantine" value={query} onChange={(event) => { setQuery(event.target.value); setPage(1) }} placeholder="QT display ID, reason, tenant" /></label><label>Status<select aria-label="Filter quarantine status" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="ALL">All statuses</option><option value="QUARANTINED">Quarantined</option><option value="CRITICAL_QUARANTINE">Critical</option></select></label><button data-control-id={control(1)} type="button" onClick={() => { setQuery(""); setFilter("ALL"); setNotice("Filters reset · isolation unchanged") }}>Reset filters</button></Panel>
     <Panel className="quarantine-list"><div className="panel-heading"><div><p className="eyebrow">ISOLATED INPUTS</p><h2>{visible.length} review items</h2></div><span className="mono">PAGE {page} / 1</span></div><div className="admin-table-wrap"><table><thead><tr><th>ITEM ID</th><th>REASON</th><th>STATUS</th><th>RETENTION</th><th>ACTIONS</th></tr></thead><tbody>{visible.map((item, index) => <tr key={item.id}><td><button className="link-button mono" data-control-id={index === 0 ? control(2) : undefined} type="button" onClick={() => choose(item.id)}>{item.displayId}</button><small className="mono">{item.tenantId}</small></td><td><span className="status status-stale">{item.reason}</span></td><td><span className={item.status === "CRITICAL_QUARANTINE" ? "status status-failed" : "status status-stale"}>{item.status}</span></td><td className="mono">{item.retention}</td><td className="actions">{index === 0 ? <><ActionButton data-control-id={control(3)} sourceId={control(3)} operationId={`quarantine-evidence-${item.id}`} state="enabled" onClick={() => choose(item.id)}>View Evidence</ActionButton><ActionButton data-control-id={control(4)} sourceId={control(4)} operationId={`quarantine-release-${item.id}`} state={item.release ? "enabled" : "disabled-unreleasable"} disabled={!item.release} disabledReason={item.releaseReason} onClick={() => openDialog("release")}>Release</ActionButton></> : <><button type="button" onClick={() => choose(item.id)}>View Evidence</button><button type="button" disabled={!item.release} title={item.releaseReason}>{item.release ? "Release" : "Release unavailable"}</button></>}</td></tr>)}</tbody></table></div><div className="quarantine-pager"><button data-control-id={control(5)} type="button" disabled={page === 1} onClick={() => setPage(1)}>Previous</button><button data-control-id={control(6)} type="button" disabled={page === 1} onClick={() => setPage(1)}>Next</button></div></Panel>
    <Panel className="quarantine-detail"><div className="detail-heading"><div><p className="eyebrow">SELECTED EVIDENCE</p><h2>{selected.displayId}</h2></div><span className="status status-blocked">{selected.status}</span></div><p>{selected.reason} · <span className="mono">{selected.id}</span></p><dl className="quarantine-fields"><div><dt>DECLARED TYPE</dt><dd>{selected.declared}</dd></div><div><dt>DETECTED TYPE</dt><dd>{selected.detected}</dd></div><div><dt>MAGIC BYTES</dt><dd>{selected.magic}</dd></div><div><dt>SIZE</dt><dd>{selected.size}</dd></div><div><dt>PARSE RESULT</dt><dd>{selected.parse}</dd></div><div><dt>RETENTION</dt><dd>{selected.retention}</dd></div></dl><div className="quarantine-isolation"><strong>ISOLATED</strong><span>No raw bytes, private paths, or downloads are exposed.</span></div><div className="quarantine-inspect"><button data-control-id={control(9)} type="button" onClick={() => setInspection("Role and scope: platform operations viewer; release requires assigned revalidation scope.")}>Inspect role and scope</button><button data-control-id={control(10)} type="button" onClick={() => setInspection(`Tenant fence: ${selected.tenantId}; cross-tenant release is denied.`)}>Inspect tenant fence</button><button data-control-id={control(11)} type="button" onClick={() => setInspection("Evidence policy: metadata only; raw bytes and private paths stay isolated.")}>Inspect isolation policy</button><button data-control-id={control(12)} type="button" onClick={() => setInspection("Audit policy: release and reject append an immutable result.")}>Inspect audit policy</button><button data-control-id={control(13)} type="button" onClick={() => { void navigator.clipboard?.writeText(selected.id); setInspection(`Copied canonical item ID ${selected.id}.`) }}>Copy canonical item ID</button></div>{inspection && <p className="admin-notice" role="status">{inspection}</p>}<h3>Review history</h3><ul>{selected.history.map((entry) => <li key={entry}>{entry}</li>)}</ul><div className="actions"><ActionButton data-control-id={control(7)} sourceId={control(7)} operationId={`quarantine-reject-${selected.id}`} state="enabled" onClick={() => openDialog("reject")}>Reject</ActionButton><ActionButton data-control-id={control(8)} sourceId={control(8)} operationId={`quarantine-release-${selected.id}`} state={selected.release ? "enabled" : "disabled-unreleasable"} disabled={!selected.release} disabledReason={selected.releaseReason} onClick={() => openDialog("release")}>Release selected</ActionButton></div><DisabledReason id={`${control(8)}-reason`} reason={selected.releaseReason} /></Panel>
    {dialog && <div className="confirm-backdrop" onKeyDown={(event) => { if (event.key === "Escape") setDialog(null) }}><Panel className="confirm" role="dialog" aria-modal="true" aria-labelledby="quarantine-confirm-title"><h2 id="quarantine-confirm-title">Confirm {dialog}</h2><p>This action applies to <b>{selected.id}</b> for tenant <b>{selected.tenantId}</b>. {dialog === "release" ? "A new linked upload enters VALIDATING; the original remains QUARANTINED." : "The input remains isolated and cannot be recovered from this view."}</p><label><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /> I understand the consequence and confirm the item and tenant.</label><div className="tenant-confirm-actions"><button data-control-id={control(14)} type="button" onClick={() => setDialog(null)}>Cancel</button><button data-control-id={control(15)} type="button" disabled={!confirmed} onClick={submit}>Confirm {dialog}</button></div></Panel></div>}
    {revalidation && <p className="admin-notice">Linked revalidation: <span className="mono">{revalidation}</span> · VALIDATING</p>}
  </div>
}
