import { randomBytes } from "node:crypto"
import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify"
import { authenticateAdminBearer, type AuthStore, type Principal } from "./auth.js"
import { IdempotencyStore, safeEnvelope, requestHash } from "./boundary.js"

export type AdminMutationJob = { id: string; tenantId: string; state: string; attempt: number; version: number }
export type AdminMutationQuarantine = { id: string; tenantId: string; state: "QUARANTINED" | "REJECTED" | "VALIDATING"; version: number }
export type AdminMutationTenant = { id: string; status: string; version: number; members: Map<string, "OWNER" | "ADMIN" | "MEMBER">; planMetadata: Record<string, string | number | boolean | null>; quotaBytes: number }
export type AdminMutationExport = { id: string; tenantId: string | null; kind: "audit" | "receipt"; state: "PENDING"; expiresAt: string }
export type AdminAuditEvent = { id: string; tenantId: string | null; actorId: string; action: string; targetType: string; targetId: string; before: unknown; after: unknown; reason: string; correlationId: string; outcome: "ALLOWED" | "DENIED"; createdAt: string }
export type AdminMutationStore = { readonly jobs: Map<string, AdminMutationJob>; readonly quarantine: Map<string, AdminMutationQuarantine>; readonly tenants: Map<string, AdminMutationTenant>; readonly exports: Map<string, AdminMutationExport>; readonly auditEvents: AdminAuditEvent[]; readonly idempotency: IdempotencyStore; readonly now: () => number }
export const createAdminMutationStore = (now = Date.now()): AdminMutationStore => ({ jobs: new Map(), quarantine: new Map(), tenants: new Map(), exports: new Map(), auditEvents: [], idempotency: new IdempotencyStore(), now: () => now })

type Body = { reason?: string; confirmTenantId?: string; confirmItemId?: string; addOrUpdate?: { userId: string; role: "OWNER" | "ADMIN" | "MEMBER" }; removeUserId?: string; planMetadata?: Record<string, string | number | boolean | null>; quotaBytes?: number; format?: "jsonl"; tenantId?: string; jobId?: string; gate?: string; q?: string; eventType?: string; outcome?: string; actor?: string; range?: string }
const id = (prefix: string): string => `${prefix}_${randomBytes(10).toString("base64url")}`
const header = (request: FastifyRequest, name: string): string | undefined => { const value = request.headers[name]; return typeof value === "string" ? value : undefined }
const role = (principal: Principal): string => principal.roles[0]?.toUpperCase().replace("-", "_") ?? ""
const fail = (reply: FastifyReply, error: unknown): void => { const code = error instanceof Error ? error.message : "INTERNAL_ERROR"; const status = code === "ADMIN_ACCESS_DENIED" || code === "ROLE_NOT_PERMITTED" ? 403 : code === "RESOURCE_NOT_FOUND" ? 404 : code === "VERSION_CONFLICT" ? 409 : 400; reply.code(status).send(safeEnvelope(new Error(code), String(reply.getHeader("x-correlation-id")))) }
const requireReason = (body: Body): string => { if (!body.reason || body.reason.length < 1 || body.reason.length > 500) throw new Error("INVALID_REQUEST"); return body.reason }
const requireVersion = (request: FastifyRequest, version: number): void => { if (header(request, "if-match") !== `W/\"${version}\"` && header(request, "if-match") !== `\"${version}\"`) throw new Error("VERSION_CONFLICT") }

export function registerAdminMutation(app: FastifyInstance, auth: AuthStore, store: AdminMutationStore, now = Date.now()): void {
  app.addHook("onRequest", async (request, reply) => { if (!request.url.startsWith("/admin/")) return; const raw = header(request, "authorization")?.startsWith("Bearer ") ? header(request, "authorization")?.slice(7) ?? "" : ""; const principal = authenticateAdminBearer(auth, raw, now); if ("code" in principal) { fail(reply, new Error(principal.code)); return } (request as FastifyRequest & { adminMutationPrincipal?: Principal }).adminMutationPrincipal = principal })
  const command = (request: FastifyRequest, targetTenant: string | null, action: (principal: Principal, correlation: string) => readonly [number, Record<string, unknown>]): readonly [number, Record<string, unknown>] => {
    const principal = (request as FastifyRequest & { adminMutationPrincipal?: Principal }).adminMutationPrincipal; if (!principal) throw new Error("ADMIN_ACCESS_DENIED")
    const tenant = targetTenant ?? principal.tenantId; const principalRole = role(principal); const assigned = principalRole === "SUPER_ADMIN" || (principalRole === "OPS_ADMIN" && auth.assignments.some((item) => item.reviewerId === principal.userId && item.scope === "TENANT" && item.tenantId === tenant))
    if (!assigned) { store.auditEvents.push({ id: id("audit"), tenantId: tenant, actorId: principal.userId, action: "ADMIN_MUTATION_DENIED", targetType: "admin", targetId: tenant, before: null, after: null, reason: "assignment required", correlationId: String(request.headers["x-correlation-id"] ?? ""), outcome: "DENIED", createdAt: new Date(store.now()).toISOString() }); throw new Error("ADMIN_ACCESS_DENIED") }
    const key = header(request, "idempotency-key"); if (!key) throw new Error("INVALID_REQUEST"); const correlation = String(request.headers["x-correlation-id"] ?? ""); const replay = store.idempotency.execute(request.method + ":" + request.url.split("?")[0], key, requestHash(request.body ?? {}), tenant, () => action(principal, correlation)); return replay.response
  }
  const mutate = async (request: FastifyRequest<{ Params: { jobId?: string; itemId?: string; tenantId?: string }; Body: Body }>, reply: FastifyReply): Promise<void> => { try { const body = request.body ?? {}; const tenantId = request.params.tenantId ?? (request.params.jobId ? store.jobs.get(request.params.jobId)?.tenantId : request.params.itemId ? store.quarantine.get(request.params.itemId)?.tenantId : null) ?? null; const result = command(request, tenantId, (principal, correlation) => { const reason = requireReason(body); const path = request.url.split("?")[0] ?? ""; if (path.endsWith("/cancel") || path.endsWith("/retry")) { const job = store.jobs.get(request.params.jobId ?? ""); if (!job || job.tenantId !== tenantId) throw new Error("RESOURCE_NOT_FOUND"); requireVersion(request, job.version); const before = { state: job.state, attempt: job.attempt, version: job.version }; if (path.endsWith("/cancel")) { if (!["QUEUED", "PREPARING", "RENDERING"].includes(job.state)) throw new Error("JOB_NOT_CANCELLABLE"); job.state = "CANCEL_REQUESTED" } else { if (!["FAILED", "CANCELLED"].includes(job.state)) throw new Error("JOB_NOT_RETRYABLE"); job.attempt += 1; job.state = "QUEUED" } job.version += 1; store.auditEvents.push({ id: id("audit"), tenantId, actorId: principal.userId, action: path.endsWith("/cancel") ? "JOB_CANCEL_REQUESTED" : "JOB_RETRY_REQUESTED", targetType: "job", targetId: job.id, before, after: { state: job.state, attempt: job.attempt, version: job.version }, reason, correlationId: correlation, outcome: "ALLOWED", createdAt: new Date(store.now()).toISOString() }); return [path.endsWith("/cancel") ? 202 : 201, { state: job.state, version: job.version }] }
      if (path.includes("/quarantine/")) { const item = store.quarantine.get(request.params.itemId ?? ""); if (!item || item.tenantId !== tenantId || body.confirmTenantId !== tenantId || body.confirmItemId !== item.id) throw new Error("QUARANTINE_RELEASE_BLOCKED"); requireVersion(request, item.version); const before = { state: item.state, version: item.version }; if (path.endsWith("/release")) { if (item.state !== "QUARANTINED") throw new Error("QUARANTINE_RELEASE_BLOCKED"); item.state = "VALIDATING" } else { if (item.state !== "QUARANTINED") throw new Error("VERSION_CONFLICT"); item.state = "REJECTED" } item.version += 1; store.auditEvents.push({ id: id("audit"), tenantId, actorId: principal.userId, action: path.endsWith("/release") ? "QUARANTINE_RELEASE_REVIEWED" : "QUARANTINE_RETAINED", targetType: "quarantine", targetId: item.id, before, after: { state: item.state, version: item.version }, reason, correlationId: correlation, outcome: "ALLOWED", createdAt: new Date(store.now()).toISOString() }); return [path.endsWith("/release") ? 202 : 200, path.endsWith("/release") ? { revalidationUploadId: id("upl"), originalQuarantineState: "QUARANTINED", state: "VALIDATING" } : { state: "rejected" }] }
      const tenant = store.tenants.get(tenantId ?? ""); if (!tenant) throw new Error("RESOURCE_NOT_FOUND"); requireVersion(request, tenant.version); const before = { status: tenant.status, members: [...tenant.members], planMetadata: tenant.planMetadata, quotaBytes: tenant.quotaBytes }; if (path.endsWith("/suspend")) tenant.status = "suspended"; else if (path.endsWith("/members")) { if (body.addOrUpdate) { if (!["OWNER", "ADMIN", "MEMBER"].includes(body.addOrUpdate.role)) throw new Error("ROLE_NOT_PERMITTED"); tenant.members.set(body.addOrUpdate.userId, body.addOrUpdate.role) } else if (body.removeUserId) tenant.members.delete(body.removeUserId); else throw new Error("INVALID_REQUEST") } else { if (body.planMetadata) tenant.planMetadata = { ...tenant.planMetadata, ...body.planMetadata }; if (body.quotaBytes !== undefined) tenant.quotaBytes = body.quotaBytes } tenant.version += 1; store.auditEvents.push({ id: id("audit"), tenantId, actorId: principal.userId, action: path.endsWith("/suspend") ? "TENANT_SUSPENDED" : path.endsWith("/members") ? "TENANT_ACCESS_CHANGED" : "BILLING_METADATA_CHANGED", targetType: "tenant", targetId: tenant.id, before, after: { status: tenant.status, members: [...tenant.members], planMetadata: tenant.planMetadata, quotaBytes: tenant.quotaBytes }, reason, correlationId: correlation, outcome: "ALLOWED", createdAt: new Date(store.now()).toISOString() }); return [200, { status: tenant.status, version: tenant.version }] }) ; reply.code(result[0]).send(result[1]) } catch (error) { fail(reply, error) } }
  app.post("/admin/jobs/:jobId/cancel", mutate); app.post("/admin/jobs/:jobId/retry", mutate); app.post("/admin/quarantine/:itemId/release", mutate); app.post("/admin/quarantine/:itemId/reject", mutate); app.patch("/admin/tenants/:tenantId/members", mutate); app.post("/admin/tenants/:tenantId/suspend", mutate); app.patch("/admin/billing/:tenantId", mutate)
  const queue = async (request: FastifyRequest<{ Body: Body }>, reply: FastifyReply): Promise<void> => { try { const result = command(request, null, (principal, correlation) => { if (role(principal) !== "SUPER_ADMIN") throw new Error("ADMIN_ACCESS_DENIED"); const draining = request.url.endsWith("/drain"); store.auditEvents.push({ id: id("audit"), tenantId: null, actorId: principal.userId, action: draining ? "JOB_QUEUE_DRAIN_REQUESTED" : "JOB_QUEUE_RESUME_REQUESTED", targetType: "queue", targetId: "authoritative", before: null, after: { draining }, reason: requireReason(request.body ?? {}), correlationId: correlation, outcome: "ALLOWED", createdAt: new Date(store.now()).toISOString() }); return [202, { draining }] }); reply.code(result[0]).send(result[1]) } catch (error) { fail(reply, error) } }
  app.post("/admin/queue/drain", queue); app.post("/admin/queue/resume", queue)
  const exports = async (request: FastifyRequest<{ Body: Body }>, reply: FastifyReply): Promise<void> => { try { const result = command(request, request.body?.tenantId ?? null, (principal, correlation) => { if (request.body?.format !== "jsonl") throw new Error("INVALID_REQUEST"); const exportItem: AdminMutationExport = { id: id("exp"), tenantId: request.body.tenantId ?? principal.tenantId, kind: request.url.includes("audit-exports") ? "audit" : "receipt", state: "PENDING", expiresAt: new Date(store.now() + 3600000).toISOString() }; store.exports.set(exportItem.id, exportItem); store.auditEvents.push({ id: id("audit"), tenantId: exportItem.tenantId, actorId: principal.userId, action: exportItem.kind === "audit" ? "AUDIT_EXPORT_CREATED" : "RECEIPT_EXPORT_CREATED", targetType: "export", targetId: exportItem.id, before: null, after: { state: exportItem.state }, reason: requireReason(request.body ?? {}), correlationId: correlation, outcome: "ALLOWED", createdAt: new Date(store.now()).toISOString() }); return [202, { exportId: exportItem.id, state: exportItem.state, expiresAt: exportItem.expiresAt, downloadReady: false }] }); reply.code(result[0]).send(result[1]) } catch (error) { fail(reply, error) } }
  app.post("/admin/audit-exports", exports); app.post("/admin/receipt-exports", exports)
  app.all("/admin/jobs/:jobId/prioritize", async (_request, reply) => { reply.code(403).send(safeEnvelope(new Error("ROLE_NOT_PERMITTED"), String(reply.getHeader("x-correlation-id")))) })
}
