export const MOTION_LOOKUP_CORPUS = [
  [
    "reference",
    [
      "reference analysis",
      "레퍼런스 분석",
      "motion reference",
      "동작 참고 분석",
      "reference 비트 분석",
      "레퍼런스 beat sheet",
      "motion 레퍼런스",
      "reference analysis!",
    ],
    "reference 데이터베이스",
  ],
  [
    "timing-easing",
    [
      "timing and easing",
      "타이밍과 이징",
      "anticipation overshoot",
      "예비동작 오버슈트",
      "12-frame anticipation",
      "8% 오버슈트",
      "frame 36 settle",
      "timing and easing!",
    ],
    "spring solver plugin",
  ],
  [
    "spatial-choreography",
    [
      "spatial choreography",
      "공간 안무",
      "motion path layout",
      "동선 배치",
      "x y 동선",
      "position 안무",
      "path 공간 구성",
      "spatial choreography!",
    ],
    "GPS route planner",
  ],
  [
    "layering",
    [
      "layering",
      "레이어 구성",
      "layer order",
      "레이어 순서",
      "z-order 레이어",
      "opacity 레이어링",
      "layer 가림 관계",
      "layering!",
    ],
    "PSD importer",
  ],
  [
    "transitions",
    [
      "transitions",
      "전환",
      "scene transition",
      "장면 전환",
      "dissolve 전환",
      "cut 장면 연결",
      "transition 오버랩",
      "transitions!",
    ],
    "database transaction",
  ],
  [
    "typography",
    [
      "kinetic typography",
      "키네틱 타이포그래피",
      "animated type",
      "움직이는 글자",
      "type 리듬",
      "tracking 애니메이션",
      "text 가독성",
      "kinetic typography!",
    ],
    "OCR 번역",
  ],
  [
    "path-morph",
    [
      "path and morph",
      "패스와 모프",
      "shape morph",
      "도형 변형",
      "SVG 모프",
      "motion path 변형",
      "path 형태 보간",
      "path and morph!",
    ],
    "raster tracing service",
  ],
  [
    "mask-matte",
    [
      "mask and matte",
      "마스크와 매트",
      "alpha matte",
      "알파 매트",
      "mask 페더",
      "matte 가시성",
      "alpha 매트 전환",
      "mask and matte!",
    ],
    "face recognition mask",
  ],
  [
    "camera-3d",
    [
      "camera and 3d",
      "카메라와 3D",
      "camera parallax",
      "카메라 원근",
      "3D depth 카메라",
      "parallax 깊이",
      "focal length 원근",
      "camera and 3d!",
    ],
    "Blender fluid simulation",
  ],
  [
    "lighting-compositing",
    [
      "lighting and compositing",
      "조명과 합성",
      "light and shadow",
      "빛과 그림자",
      "blend mode 합성",
      "drop-shadow 조명",
      "compositing 색 관계",
      "lighting and compositing!",
    ],
    "ray tracing farm",
  ],
  [
    "effects",
    [
      "effects",
      "효과",
      "visual effect",
      "시각 효과",
      "effect template",
      "blur 효과",
      "approved effect 적용",
      "effects!",
    ],
    "third party preset marketplace",
  ],
  [
    "audio",
    [
      "audio synchronization",
      "오디오 동기화",
      "audio cue",
      "음향 큐",
      "beat 오디오 싱크",
      "audio cue 정렬",
      "audio synchronization!",
      "dB 레벨 동기화",
    ],
    "speech transcription",
  ],
  [
    "expressions",
    [
      "expressions",
      "표현식",
      "expression template",
      "표현식 템플릿",
      "oscillate 표현식",
      "frequency 템플릿",
      "typed expression 파라미터",
      "expressions!",
    ],
    "arbitrary javascript execution",
  ],
  [
    "interaction",
    [
      "interaction",
      "인터랙션",
      "interactive motion",
      "상호작용 모션",
      "hover 인터랙션",
      "keyboard 반응",
      "pointer 상태 전환",
      "interaction!",
    ],
    "multiplayer cursor server",
  ],
  [
    "verification-accessibility",
    [
      "verification and accessibility",
      "검증과 접근성",
      "motion verification",
      "모션 검증",
      "predicate 접근성",
      "reduced motion 검증",
      "frame hash 접근성",
      "verification and accessibility!",
    ],
    "legal compliance certification",
  ],
] as const;
