import { expect, test } from "@playwright/test"

test.describe("admin shell and dashboard @admin-dashboard @admin-shell", () => {
  test("shows scoped operational summary and narrow navigation", async ({ page }) => {
    await page.goto("/admin")
    await expect(page.getByRole("heading", { name: "Admin dashboard" })).toBeVisible()
    await expect(page.getByText("Platform scope · Operations")).toBeVisible()
    await expect(page.getByText("What changed")).toBeVisible()
    await page.getByRole("button", { name: "Scope details" }).click()
    await expect(page.getByRole("dialog")).toContainText("server-side tenant assignments")
    await page.getByRole("button", { name: "Close scope details" }).click()
    await page.setViewportSize({ width: 520, height: 800 })
    await page.getByRole("button", { name: "Menu" }).click()
    await expect(page.getByRole("navigation")).toBeVisible()
    await expect(page.getByRole("link", { name: "Jobs", exact: true })).toHaveAttribute("href", "/admin/jobs")
  })
})

test("keeps the verified queue contract @admin-jobs", async ({ page }) => {
  await page.goto("/admin/jobs")
  await expect(page.getByRole("heading", { name: "Queue & Delivery" })).toBeVisible()
  const controls = page.locator('[data-control-id^="job_queue_delivery:"]')
  await expect(controls).toHaveCount(30)
})

test("recreates immutable audit search, detail, and scoped export @admin-audit", async ({ page }) => {
  await page.goto("/admin/audit")
  await expect(page.getByRole("heading", { name: "Audit log" })).toBeVisible()
  const seen = new Set<string>()
  const collect = async () => { const values = (await page.locator('[data-control-id^="admin_audit_log:"]:visible').evaluateAll((nodes) => nodes.map((node) => node.getAttribute("data-control-id")))).filter((value): value is string => value !== null); expect(new Set(values).size).toBe(values.length); values.forEach((value) => seen.add(value)) }
  await collect()
  await page.getByLabel("Event type").selectOption("JOB_CANCEL_REQUESTED")
  await expect(page.getByText("1 events")).toBeVisible()
  await page.getByLabel("Outcome").selectOption("SUCCESS")
  await page.getByLabel("Actor").selectOption("ops.admin@rvs.local")
  await page.locator("label").filter({ hasText: /^Tenant/ }).locator("select").selectOption("tenant_alpha")
  await page.getByLabel("Date range").selectOption("90d")
  await page.getByRole("button", { name: "Clear filters" }).click()
  await page.getByLabel("Search events and IDs").fill("corr_7d8f2a11")
  await expect(page.getByText("1 events")).toBeVisible()
  await expect(page.locator("tbody tr").first()).toContainText("2026-08-22 09:12:44 UTC")
  await expect(page.locator("body")).not.toContainText("/private/")
  await expect(page.locator("body")).not.toContainText("sk_live")
  await expect(page.locator("body")).not.toContainText("card_number")
  await collect()
  await page.getByRole("button", { name: "View details" }).click()
  await expect(page.getByRole("dialog")).toContainText("corr_7d8f2a11")
  await expect(page.getByRole("dialog").getByRole("link", { name: "Open related object" })).toHaveAttribute("href", /\/admin\/audit\?event=/)
  await page.getByRole("button", { name: "Copy correlation ID" }).click()
  await expect(page.getByRole("status")).toContainText("Copied correlation ID")
  await collect()
  await page.getByRole("button", { name: "Close audit details" }).click()
  await page.getByRole("button", { name: "Export filtered" }).click()
  await expect(page.getByRole("dialog")).toContainText("scoped export")
  await collect()
  await page.getByRole("button", { name: "Confirm export" }).click()
  await expect(page.getByText("export artifact expires after 90 days")).toBeVisible()
  await expect(page.getByText(/No edit or delete/i)).toHaveCount(0)
  await page.getByLabel("Outcome").selectOption("INVALID")
  await expect(page.getByText("0 events")).toBeVisible()
  await page.getByLabel("Search events and IDs").fill("__error__")
  await expect(page.locator(".audit-empty[role=alert]")).toContainText("query failed")
  await page.getByRole("button", { name: "Retry query" }).click()
  await page.goto("/admin/audit?role=viewer")
  await page.getByRole("button", { name: "Export filtered" }).click()
  await expect(page.getByRole("dialog")).toContainText("Viewer role cannot create export artifacts")
  await expect(page.getByRole("button", { name: "Confirm export" })).toBeDisabled()
  await page.getByRole("button", { name: "Cancel" }).click()
  await collect()
  expect([...seen].sort()).toEqual(Array.from({ length: 15 }, (_, index) => `admin_audit_log:${index + 1}`).sort())
})
