import { expect, test } from "@playwright/test"

test("covers quarantine evidence, filters, canonical IDs, confirmations, and isolation @admin-quarantine", async ({ page }) => {
  const seen = new Set<string>()
  const collect = async () => {
    const values = await page.locator('[data-control-id^="admin_quarantine:"]').evaluateAll((elements) => elements.map((element) => element.getAttribute("data-control-id")))
    expect(new Set(values).size).toBe(values.length)
    for (const value of values) if (value) seen.add(value)
  }
  await page.goto("/admin/quarantine")
  await expect(page.getByRole("heading", { name: "Quarantine" })).toBeVisible()
  await collect()
  await expect(page.getByRole("button", { name: "QT-8992-FX" })).toBeVisible()
  await expect(page.locator('a[href*="QT-"]')).toHaveCount(0)
  await page.getByLabel("Search quarantine").fill("MALWARE")
  await expect(page.getByText("QT-8993-AL")).toBeVisible()
  await page.getByLabel("Search quarantine").fill("")
  await page.getByLabel("Filter quarantine status").selectOption("CRITICAL_QUARANTINE")
  await expect(page.getByText("MALWARE_SIGNATURE_DETECTED")).toBeVisible()
  await page.getByRole("button", { name: "Reset filters" }).click()
  await page.getByRole("button", { name: "View Evidence" }).first().click()
  await expect(page.getByRole("heading", { name: "QT-8992-FX" })).toBeVisible()
  await expect(page.getByText("ftyp signature absent")).toBeVisible()
  await expect(page.getByText("No raw bytes, private paths, or downloads are exposed.")).toBeVisible()
  await page.getByRole("button", { name: "Inspect role and scope" }).click()
  await expect(page.locator(".quarantine-detail [role=status]")).toContainText("Role and scope")
  await page.getByRole("button", { name: "Inspect tenant fence" }).click()
  await expect(page.locator(".quarantine-detail [role=status]")).toContainText("Tenant fence")
  await page.getByRole("button", { name: "Inspect isolation policy" }).click()
  await expect(page.locator(".quarantine-detail [role=status]")).toContainText("Evidence policy")
  await page.getByRole("button", { name: "Inspect audit policy" }).click()
  await expect(page.locator(".quarantine-detail [role=status]")).toContainText("Audit policy")
  await page.getByRole("button", { name: "Copy canonical item ID" }).click()
  await expect(page.locator(".quarantine-detail [role=status]")).toContainText("qitem_8992_fx")
  await page.getByRole("button", { name: "Release selected" }).click()
  await expect(page.getByRole("dialog")).toBeVisible()
  await expect(page.getByRole("dialog")).toContainText("qitem_8992_fx")
  await expect(page.getByRole("dialog")).toContainText("tnt_aegis")
  await expect(page.getByRole("dialog").getByRole("button", { name: "Confirm release" })).toBeDisabled()
  await page.getByRole("checkbox").check()
  await collect()
  await page.getByRole("dialog").getByRole("button", { name: "Confirm release" }).click()
  await expect(page.locator(".admin-page > p[role=status]").first()).toContainText("VALIDATING")
  await expect(page.locator(".admin-page > p[role=status]").first()).toContainText("remains QUARANTINED")
  await page.getByRole("button", { name: "Reject" }).click()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await page.getByRole("button", { name: "Reject" }).click()
  await page.getByRole("checkbox").check()
  await collect()
  await page.getByRole("button", { name: "Confirm reject" }).click()
  await expect(page.locator(".admin-page > p[role=status]").first()).toContainText("input remains isolated")
  await collect()
  expect([...seen].sort()).toEqual(Array.from({ length: 15 }, (_, index) => `admin_quarantine:${index + 1}`).sort())
  expect(seen.size).toBe(15)
})
